### ISSUE TITLE
Improvement for: seeing who is getting 'notifications' for work item

### ISSUE THREAD

**Issue by SeanMiddleton** [alejandro5042/azdo-userscripts#119]
Alejandro B. added the ability to see who is 'Following' a work item.  

I am hoping for an OR of both of the below such that all possible notifications are visible:

- 'Following'
- Rules such as below is set such that a person would get a notification:
     - 'A work item I created is changed'
     - 'A work item assigned to me is changed'

This would allow me to tell, through all means, which persons will be notified.  For example, our team mostly uses the rules and not 'Follow'.  So, it's difficult for me to tell who will get a notification just through 'Follow' listing.  Thanks.

Here's the Teams thread which caused the script to me created (and my original request):
https://teams.microsoft.com/l/message/19:ec5c5db6df02420aa84e580ba7c6c92b@thread.tacv2/1600440116221?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=6ed8db9a-c7ab-481b-8e9b-ee5608937d8a&parentMessageId=1600440116221&teamName=ASW%20%26%20DSW&channelName=General&createdTime=1600440116221

**Comment by alejandro5042** [comment]
Thanks Sean! I'll at least take a look at how feasible this is for i85.

**Comment by alejandro5042** [comment]
Sadly, this is not possible. AzDO does not provide an API to determine which subscriptions would fire for a specific work item.

Closing this work item for now, but I will ask Microsoft about such an API.
