### ISSUE TITLE
Not working in Firefox (in one user environment, so far)

### ISSUE THREAD

**Issue by jerone** [alejandro5042/azdo-userscripts#135]
It appears that this userscript is not working in Firefox anymore. I know it did work.

Below are screenshots of the same page in Chrome (where it does work) and Firefox (where it does not work).

I cannot confirm if this is an Firefox, Tampermonkey or userscript error.

## Screenshots
Screenshot Chrome:
![image](https://user-images.githubusercontent.com/55841/100908173-7e7c1a80-34cb-11eb-8b8f-c6415ede751e.png)

Screenshot Firefox:
![image](https://user-images.githubusercontent.com/55841/100908416-c4d17980-34cb-11eb-8236-36dc9ba62f94.png)

## Logs
Can't find any errors in the developer console.

## Context
- Extension Version: 2.51.0 (latest)
- Browser: Firefox 83.0 (64-bit)
- URL: `dev.azure.com/account`
- "New Repos pull request experience" disabled

**Comment by alejandro5042** [comment]
Thanks for the report!

I will try to reproduce and see what I find out. Maybe it is just the fun trophies feature that is busted?

From the limited usage data I have (just the update check), I know we have ~100 Firefox users using the userscript daily, and this is the first such report. The last userscript update was 16 days ago, and Firefox 83.0 (what you're using) has been out since Nov 17. So it doesn't seem like it is a widespread issue... can you check if the userscript features in the PR dashboard on Firefox still work?

**Comment by jerone** [comment]
If I remember correctly, it also didn't work on the PR dashboard. Right now I'm not behind my work machine (the one mentioned above). I'll let know asap.

Weirdly enough, the script is working on my home computer in Firefox.

**Comment by alejandro5042** [comment]
@jerone Have you resolved your issue? Could it be an extension or corporate policy that is affecting your work Firefox?

I wonder, if you install dev Firefox (which I believe is side-by-side) on your work machine, does the extension work there?

**Comment by jerone** [comment]
@alejandro5042 I'm still experiencing this issue on one environment. 

There are not corporate policies.

The only other extensions that could interfere is Adblock, "I don't care about cookies" & Stylish. All of which I disabled without any difference.

I have no other UserScript running in TamperMonkey on Azure DevOps that could interfere.

I'm 100% sure I have the latest version.

TamperMonkey is confirming that the script is activated.

I tried putting an console.log message in the source code, but it didn't log!

I'm kinda lost.

**Comment by alejandro5042** [comment]
Maybe try reinstalling TamperMonkey and then also the userscript? Or try another [side-by-side] version of FireFox to see if it reproduces there?

It does seem not to be a userscript issue but something specifically about your FireFox-TamperMonkey setup on that one machine...

**Comment by jerone** [comment]
I came to the same conclusion. Once I have time I'll try to reinstall everything. In the meantime I'll close this issue, as it's just me and probably something with my environment.

**Comment by jerone** [comment]
Thus... right now it's working again. 
No update from this userscript, no update from Firefox and no updates from extensions.
So, maybe it was something weird with Azure DevOps caching on one machine.
