### ISSUE TITLE
Feature: Add the ability to hide/collapse the "Created by me" reviews.

### ISSUE THREAD

**Issue by bgianfo** [alejandro5042/azdo-userscripts#20]
## Is your feature request related to a problem? Please describe.
It would be useful to be able  to hide the list of reviews that you have created in AzureDevOps.
For example at the moment I have ~12 PR's created by me, in various stages of the development cycle. I don't really care to see  these PR's as I'm doing code reviews for my collaborators. It's just wasted real-estate. 

## Describe the solution you'd like
The functionality already seems to exist to add a collapsable list to the assigned reviews. Potentially this some functionality could be hooked up to work on the "Create by me" reviews. 

## Describe alternatives you've considered
I don't believe there is an alternative available besides just living without the feature. 

## Additional context
N/A

**Comment by alejandro5042** [comment]
Thank you for this suggestion. I would also benefit from this!

Note: There are two PR dashboards:

- A per-repo one at https://dev.azure.com/ORG/PROJECT/_git/REPO/pullrequests?_a=mine
- An org-wide one at https://dev.azure.com/ORG/_pulls

The org-wide PR listing shows you PRs across all your repos and allows you to collapse your PRs:

![image](https://user-images.githubusercontent.com/3143819/66657120-e2c38700-ec04-11e9-8bf6-dcf4893dbfec.png)

Maybe this view is better for you?

Either way, I believe sorting your PRs into buckets such as Drafts and Published might still be useful.

Thoughts welcomed.

**Comment by bgianfo** [comment]
I mostly focus on the per-repo dashboard, and don't pay much attention to the org-wide one.

**Comment by alejandro5042** [comment]
Fixed in [latest release](https://github.com/alejandro5042/azdo-userscripts/releases/tag/v2.32.0). Simply update your script via Tampermonkey. Cheers!
