### ISSUE TITLE
Not working because of tippy.js exception

### ISSUE THREAD

**Issue by jerone** [alejandro5042/azdo-userscripts#205]
The userscript is not working for some time now. Today I investigated why this happened. After some debugging I found out that the included resource tippy.js was the issue (see screenshot).

Removing the following line from the source make the userscript working again.
```
// @require      https://unpkg.com/tippy.js@6#sha384-AiTRpehQ7zqeua0Ypfa6Q4ki/ddhczZxrKtiQbTQUlJIhBkTeyoZP9/W/5ulFt29
```

I have verified this on my work and personal account.

## Logs
![image](https://user-images.githubusercontent.com/55841/207324934-b4698d02-47ec-46c2-8bdd-d71fa7d827d7.png)

## Context
- Userscript Manager: Tampermonkey, version 4.18.1
- Userscript version: 3.4.6
- Browser: Firefox 107.0.1 64-bit for Windows
- URL: `dev.azure.com/account`

**Comment by alejandro5042** [comment]
Ugh, that's no good.

I just checked with latest Microsoft Store version of Firefox 108.0.1 (64 bit) on Windows 10 -- userscript works. Using Violentmonkey 2.13.3.

The userscript is also working on Chrome/Edge.

Could you try with Violentmonkey and see if it works? If not, could you try upgrading Firefox to 108?

Let's try to isolate this issue and fix it for ya!

**Comment by jerone** [comment]
Updating to Firefox 108 didn't change anything.

I tried changing the way the script is loaded with `run-at` (`document-start`, `document-body`, `document-end`, `document-idle`, ...); no success. 

I tried [Tampermonkey Beta](https://www.tampermonkey.net/changelog.php?ext=dhdg&show=firb); no success.

I tried Violentmonkey, which does work. Just not happy about it security:
> This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing.

Based on [this comment](https://github.com/atomiks/tippyjs/issues/1040#issuecomment-1100918572), it looks like an race-condition:
> `@popperjs/core` must always be loaded _before_ `tippy.js`

Sadly, Tampermonkey's [documentation](https://www.tampermonkey.net/documentation.php?version=4.19.6176&ext=firb&updated=true#_require) doesn't mention anything about the order of loading of `@require` headers.

**Comment by jerone** [comment]
Yes, I can confirm, after switching back from Violentmonkey to Tampermonkey, that the latest version (3.6.0) is working correctly again.

Thank you for letting me know.
