### ISSUE TITLE
Doesn't work with new repo listing UX

### ISSUE THREAD

**Issue by alejandro5042** [alejandro5042/azdo-userscripts#30]
When enabling this preview feature:

![image](https://user-images.githubusercontent.com/3143819/67801041-6929f680-fa56-11e9-8e89-17ac15892101.png)

The UI is totally different and the dashboard sorting doesn't work (but doesn't break the page either).

## Context
- Extension Version: All
- Browser: All
- URL: All

**Comment by bgianfo** [comment]
Looks like they are rolling out the change to make this the default and there is no way to disable it. 😟

**Comment by alejandro5042** [comment]
Yeah... I'll be updating this userscript to make it work for the new experience very soon. I'm working with the Azure DevOps team who is making this change.

**Comment by alejandro5042** [comment]
You can still disable it at the account level, or at least I can.

**Comment by alejandro5042** [comment]
Closing this one in favor of #80.
