### ISSUE TITLE
Fix PR dashboard under new PR experience

### ISSUE THREAD

**Issue by jerone** [alejandro5042/azdo-userscripts#80]
Will this userscript be ready for the New Pull Request Experience for Azure Repos: https://devblogs.microsoft.com/devops/introducing-the-new-pull-request-experience-for-azure-repos/ ?

## Context
- Extension Version: 2.41.4
- Browser: Firefox 75.0 (64-bit)
- URL: `dev.azure.com/account`

**Comment by alejandro5042** [comment]
@jerone Absolutely. I plan to make it work for the New PR experience within the next few weeks. I'm meeting with the Microsoft PMs responsible for Azure Repos this Tuesday to discuss how else they plan to change it, give feedback, perhaps push more userscript features into AzDO (hello PR file checkboxes! they started here 😄), and once I have a better picture of all that, I'll make the updates necessary to keep this userscript up-and-running!

**Comment by jerone** [comment]
@alejandro5042 You have something I can test? Love to use this US again.

**Comment by alejandro5042** [comment]
I did in fact meet with Microsoft regarding the new PR experience 2 weeks ago. They were very receptive to my feedback. Knowing a little more about their plans, I'm gonna start porting the userscript to work with the latest preview here.

To prioritize the various features, what part of the userscript do you miss the most?

**Comment by alejandro5042** [comment]
Note to self: The new trophies feature has a prototype port to the new experience, as mentioned in #82.

**Comment by jerone** [comment]
[**@alejandro5042**](https://github.com/alejandro5042) commented on [Jun 6, 2020, 5:39 AM GMT+2](https://github.com/alejandro5042/azdo-userscripts/issues/80#issuecomment-639971560 "2020-06-06T03:39:48Z - Replied by Github Reply Comments"):
> I did in fact meet with Microsoft regarding the new PR experience 2 weeks ago. They were very receptive to my feedback. Knowing a little more about their plans, I'm gonna start porting the userscript to work with the latest preview here.

Great to hear that!

> To prioritize the various features, what part of the userscript do you miss the most?

Well, from the features listed on the readme, that have not already been implemented by Microsoft, I would like to see build status on PRs being ported over. And how many files the reviewer needs to review feature was useful too.

Also, the newly added PR trophies look very cool to have in the new PR experience.

**Comment by alejandro5042** [comment]
Addressed in latest version. LMK if you have any suggestions!
